---
# Authenticate with Prism Central and and store session cookies.
# Minor changes to original code provided by the mbach04.nutanix_vm_provisioner ansible role.
- name: Authenticate to Prism Central 
  uri:
    url: "{{ pc_api_url }}/clusters/list"
    body:
      kind: cluster
      sort_order: ASCENDING
      offset: 0
      length: 10
      sort_attribute: ''
    method: POST
    validate_certs: no
    force_basic_auth: yes
    body_format: json
    user: "{{ prism_user }}"
    password: "{{ prism_password }}"
    status_code: 200
    return_content: yes
  register: pc_login
  ignore_errors: yes

- name: Store session cookie for Prism Central
  set_fact:
    pc_session_cookie: "{{ pc_login.set_cookie }}"

- name: Debug | Print session cookie for Prism Central
  debug:
    msg: "Session cookie for Prism Central is {{ pc_session_cookie }}"
  when: global_debug|bool